from __future__ import annotations

from typing import Any


DEFAULT_UI_LANGUAGE = "en"
SUPPORTED_UI_LANGUAGES = ("en", "zh-TW", "ja")

_LANGUAGE_ALIASES = {
    "zh": "zh-TW",
    "zh-hant": "zh-TW",
    "zh-tw": "zh-TW",
    "zh-hk": "zh-TW",
    "zh-mo": "zh-TW",
    "en": "en",
    "en-us": "en",
    "en-gb": "en",
    "ja": "ja",
    "ja-jp": "ja",
    "jp": "ja",
}

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "zh-TW": {
        "settings_title": "設定",
        "settings_subtitle": "管理翻譯、OCR、外觀和掃描行為。 (・ω・)ノ",
        "settings_close": "關閉",
        "settings_theme_mode": "主題風格",
        "settings_ui_language": "介面語言",
        "settings_knowledge_placeholder": "輸入遊戲或漫畫名稱 (・ω・)",
        "settings_knowledge_research": "幫我查這個作品 (๑•̀ㅂ•́)و",
        "settings_knowledge_update": "更新小本本 (´▽｀)",
        "settings_knowledge_building": "正在查資料中… (｡•ㅅ•｡)",
        "settings_knowledge_progress": "正在查資料中… {percent}% (｡•ㅅ•｡)",
        "settings_knowledge_ready": "✓ 小本本已建立完成囉！ (๑•̀ㅂ•́)و✧",
        "settings_knowledge_missing": "尚未建立小本本 (・ω・)",
        "settings_knowledge_unavailable": "研究功能尚未設定好喔 (｡•́︿•̀｡)",
        "settings_knowledge_failed": "小本本建立未完成，其他設定仍可使用喔～ (｡•ㅅ•｡)",
        "settings_knowledge_model_hint": "選擇研究與萃取使用的模型 (・ω・)",
        "settings_knowledge_sources_placeholder": "選填：公開來源網址，以空白分隔；留空則自動搜尋 (・ω・)",
        "settings_knowledge_review_title": "確認研究候選包 (・ω・)",
        "settings_knowledge_review_message": "{title}\n\n已讀取 {sources} 個來源，整理出 {entries} 筆條目；另有 {conflicts} 筆衝突、{rejected} 筆低信心或無效資料未採用。要將這份候選資料存成未啟用的小本本嗎？ (◍•ᴗ•◍)",
        "settings_knowledge_not_saved": "候選資料未儲存 (・ω・)",
        "settings_save_failed": "設定無法儲存，請檢查檔案權限或稍後重試喔 (｡•́︿•̀｡)",
        "settings_save_failed_exit_prompt": "一般設定無法儲存。要放棄尚未儲存的變更並結束嗎？選「否」可返回重試喔！ (｡•ㅅ•｡)",
        "worker.status.scan_cancelled": "掃描已取消 (・ω・)",
        "controller.window_title": "CloudHime 雲朵翻譯姬",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI 翻譯",
        "controller.button.fullscreen": "全螢幕",
        "controller.button.region": "框選區域",
        "controller.button.stop": "停止",
        "controller.button.auto_scan": "自動掃描",
        "controller.button.auto_wait": "暫停・{seconds} 秒",
        "controller.button.auto_busy": "暫停・翻譯中",
        "controller.button.auto_resume": "繼續自動掃描",
        "controller.tooltip.auto_scan": "依選定間隔掃描；再按可暫停並保留字幕，「停止」會清除字幕喔！ (◍•ᴗ•◍)",
        "controller.tooltip.auto_resume": "繼續依間隔掃描；等待期間保留目前字幕～ (´▽｀)",
        "controller.status.auto_paused": "自動掃描已暫停，字幕留著給主人慢慢讀；按「繼續自動掃描」接著翻譯囉～ (*´∀`)",
        "selection.hint.drag": "拖曳框住想讀的文字・按 Esc 可取消並保留原模式與範圍 (・ω・)ノ",
        "selection.hint.size": "{width} × {height}・放開滑鼠就選好這個範圍囉！ (๑•̀ㅂ•́)و",
        "selection.hint.too_small": "{width} × {height}・範圍有點太小，請拉到至少 20 × 20 喔～ (｡•ㅅ•｡)",
        "controller.status.selection_cancelled": "已取消框選，為主人保留原本的模式與範圍囉！ (´▽｀)",
        "controller.button.random_scan_prefix": "隨機",
        "controller.button.now": "立即翻譯",
        "controller.button.wait": "等待 {seconds} 秒",
        "controller.button.translating": "翻譯中…",
        "controller.hint.fullscreen": "第一次使用？建議先選「框選區域」試試一小段文字～全螢幕模式會讀取整個畫面喔！ (◍•ᴗ•◍)",
        "controller.hint.region": "範圍選好囉，按「立即翻譯」看結果；再按「框選區域」可重新選取～ (・ω・)ノ",
        "controller.tooltip.region": "拖曳框選翻譯範圍；Esc 取消框選 (・ω・)ノ",
        "controller.tooltip.minimize": "最小化",
        "controller.tooltip.stop": "停止翻譯並清除字幕 (Esc) (・∀・)",
        "controller.tooltip.interval": "自動掃描間隔；實際時間會依隨機範圍微調喔 (・ω・)",
        "controller.scan_interval.approx": "約 {seconds} 秒",
        "controller.tooltip.settings": "設定",
        "controller.tooltip.hotkey": "快捷鍵：{shortcut}",
        "controller.tooltip.close": "關閉",
        "controller.status.ready": "把畫面上的外語，翻成主人看得懂的溫暖文字～ (◍•ᴗ•◍)",
        "controller.status.ai_model_ready": "目前 AI 模型：{model}",
        "controller.status.auto_scanning": "{prefix} 自動掃描中... (・ω・)",
        "controller.status.auto_stopped": "⏸ 自動掃描已停止 (・∀・)",
        "controller.status.shutting_down": "正在等待背景工作結束後關閉，請稍候一下喔… (｡•ㅅ•｡)",
        "controller.status.immediate_scanning": "⚡ 立即掃描中... (๑•̀ㅂ•́)و",
        "controller.status.need_api_key": "請先至設定頁面輸入 Google API KEY 喔 (｡•ㅅ•｡)",
        "controller.status.need_region": "請先設定框選區域喔 (・ω・)ノ",
        "controller.status.region_ready": "範圍選好囉：{size}，隨時可以開始翻譯！ (๑•̀ㅂ•́)و",
        "controller.status.capture_running": "🖼 截圖翻譯進行中... (・ω・)",
        "controller.status.cold_down": "⚡ 稍候冷卻充電中... (´ω｀*)",
        "controller.status.ai_model_auto_switch": "AI 模型自動切換：{old_label} -> {new_label} (・ω・)",
        "controller.status.ai_model_full_switch": "{current} 額度已滿，下一次會自動切換到 {backup} 喔！ (｡•ㅅ•｡)",
        "controller.status.ai_model_full_google": "{current} 已滿 {limit}/{limit}，先幫主人改用 Google 服務囉！ (o´ω`o)",
        "controller.mode.fullscreen": "🖥 模式：全螢幕",
        "controller.mode.relief": "🧩 模式：浮雕",
        "controller.mode.screenshot": "🖼 模式：截圖",
        "controller.mode.bubble": "💬 模式：氣泡",
        "controller.mode.scan_fullscreen": "全螢幕",
        "controller.mode.scan_region": "區域",
        "worker.status.threshold_tuning": "🔎 局部微調閥值中... (｡•ㅅ•｡)",
        "worker.status.sentence_recheck": "🧠 句子完整度複判中... (*´∀`)",
        "worker.status.no_ocr_backend": "沒有可用的文字辨識引擎。請到「設定 → 擷取與顯示」確認或安裝 OCR 引擎喔 (｡•ㅅ•｡)",
        "worker.status.windows_ocr_unavailable": "Windows OCR 語言功能目前不可用。請在 Windows 設定的「時間與語言 → 語言與地區」安裝 OCR 語言，或在 CloudHime 啟用其他 OCR 引擎喔 (｡•ㅅ•｡)",
        "worker.status.capture_failed": "無法讀取畫面，請切回要翻譯的視窗再試一次喔（{error}） (｡•́︿•̀｡)",
        "worker.status.screenshot_requires_ai": "目前未取得可翻譯的文字。請選支援圖片的引擎，或框選更清楚的文字範圍喔 (｡•ㅅ•｡)",
        "worker.status.screenshot_translating": "🖼 截圖模式翻譯中... (・ω・)",
        "worker.status.screenshot_failed": "截圖翻譯未完成，請檢查引擎設定與網路連線後重試喔（{error}） (｡•́︿•̀｡)",
        "worker.status.screenshot_empty": "引擎沒有回傳翻譯，請檢查引擎設定或重新框選畫面再試一次喔 (｡•ㅅ•｡)",
        "worker.status.screen_static": "♻️ 畫面靜止未變動 (・∀・)",
        "worker.status.screenshot_done": "✅ 截圖翻譯完成囉！ ヽ(・∀・)ﾉ",
        "worker.status.smart_crop": "🧭 智慧裁切分析中... (・ω・)",
        "worker.status.scanning_translating": "🔍 掃描與翻譯中... (๑•̀ㅂ•́)و",
        "worker.status.recognition_error": "❌ 文字辨識遇到狀況 (｡•́︿•̀｡)",
        "worker.status.crop_retry_full": "🧭 智慧裁切結果較少，改用全畫面重試中... (｡•ㅅ•｡)",
        "worker.status.crop_retry_rotate": "框選區域沒有掃到文字，正在旋轉角度重試中... (・ω・)",
        "worker.status.crop_retry_zoom": "框選區域沒有掃到文字，請試著框大一點或調整角度喔 (｡•ㅅ•｡)",
        "worker.status.comic_retry": "📚 漫畫頁切片重試中... (*´∀`)",
        "worker.status.best_threshold": "✨ 已選最佳閥值 {threshold} (๑•̀ㅂ•́)و",
        "worker.status.ai_big_translation": "🧠 AI 大圖翻譯處理中... (・ω・)",
        "worker.status.google_translation": "🌐 Google 翻譯中... (・ω・)",
        "worker.status.local_gemma_translation": "🧠 本機 Gemma 翻譯中... (๑•̀ㅂ•́)و",
        "worker.status.local_gemma_batch": "🧠 本機 Gemma 正在補翻 {count} 段... (｡•ㅅ•｡)",
        "worker.status.local_gemma_progress": "🧠 本機 Gemma {index}/{count} (・ω・)",
        "worker.status.exact_frame_cache": "♻️ 畫面完全相同（已使用快取） ( ´ ▽ ` )ﾉ",
        "worker.status.batch_translate": "{icon} {prefix} 批次補翻 {count} 段... (｡•ㅅ•｡)",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total} (・ω・)",
        "worker.status.translation_done": "✅ 翻譯完成囉！ ヽ(・∀・)ﾉ",
        "worker.status.translation_failed": "這次翻譯未完成，請檢查引擎設定與連線後重試喔 (｡•́︿•̀｡)",
        "worker.status.translation_incomplete": "部分文字保留原文，翻譯未完成。請檢查翻譯引擎後重試喔 (｡•ㅅ•｡)",
        "worker.status.translation_rate_limited": "Google 翻譯目前受到流量限制，請稍候重試或切換翻譯引擎喔 (´・ω・)",
        "worker.status.no_text": "沒找到可辨識的文字，試著框選更清楚的文字區域喔～ (｡•ㅅ•｡)",
        "controller.hint.region_empty": "先框住一小段清楚的外文，再按「立即翻譯」就可以囉！ (・ω・)ノ",
        "controller.engine.google": "Google 翻譯",
        "controller.engine.local_gemma": "本機 Gemma",
        "controller.engine.online_gemma": "線上 Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "需網路連線",
        "controller.engine.state.configured": "金鑰已設定，連線未驗證 (・ω・)",
        "controller.engine.state.setup": "需要設定金鑰喔 (｡•ㅅ•｡)",
        "controller.engine.state.preparing": "模型準備中，請稍候喔 (◍•ᴗ•◍)",
        "controller.engine.state.ready": "模型已就緒！ (๑•̀ㅂ•́)و✧",
        "controller.engine.state.failed": "模型需要確認設定喔 (｡•́︿•̀｡)",
        "controller.engine.state.unverified": "模型尚未就緒 (｡•ㅅ•｡)",
        "controller.engine.pending": "{name} 尚待設定完成喔 (｡•ㅅ•｡)",
        "controller.engine.change": "切換引擎",
        "controller.engine.settings_description": "開啟翻譯引擎設定，查看需求與資料去向 (・ω・)ノ",
        "controller.engine.data.google": "辨識文字會送往 Google；雲端 OCR 啟用時也會送出畫面影像喔！ (o´ω`o)",
        "controller.engine.data.local_gemma": "本機模型在裝置端處理內容；若啟用雲端 OCR、遠端端點或線上備援仍可能送出內容喔！ (o´ω`o)",
        "controller.engine.data.online_gemma": "文字或畫面影像會送往 Google；其他備援依引擎設定而定喔～ (o´ω`o)",
        "controller.engine.data.luna": "文字或畫面影像會送往 OpenAI；其他備援依引擎設定而定喔～ (o´ω`o)",
    },
    "en": {
        "settings_title": "Settings",
        "settings_subtitle": "Manage translation, OCR, appearance, and scan behavior. (・ω・)ノ",
        "settings_close": "Close",
        "settings_theme_mode": "Theme",
        "settings_ui_language": "UI Language",
        "settings_knowledge_placeholder": "Enter game or manga title (・ω・)",
        "settings_knowledge_research": "Research this work (๑•̀ㅂ•́)و",
        "settings_knowledge_update": "Update knowledge pack (´▽｀)",
        "settings_knowledge_building": "Researching… (｡•ㅅ•｡)",
        "settings_knowledge_progress": "Researching… {percent}% (｡•ㅅ•｡)",
        "settings_knowledge_ready": "✓ Knowledge pack ready! (๑•̀ㅂ•́)و✧",
        "settings_knowledge_missing": "Not created yet (・ω・)",
        "settings_knowledge_unavailable": "Research is not configured yet (｡•́︿•̀｡)",
        "settings_knowledge_failed": "Build failed; other settings are still available. (｡•ㅅ•｡)",
        "settings_knowledge_model_hint": "Choose the research extraction model (・ω・)",
        "settings_knowledge_sources_placeholder": "Optional public URLs separated by spaces; leave blank to search (・ω・)",
        "settings_knowledge_review_title": "Confirm research candidate (・ω・)",
        "settings_knowledge_review_message": "{title}\n\nRead {sources} sources and extracted {entries} entries; {conflicts} conflicts and {rejected} low-confidence or invalid items were excluded. Save this candidate as an inactive knowledge pack? (◍•ᴗ•◍)",
        "settings_knowledge_not_saved": "Candidate was not saved (・ω・)",
        "settings_save_failed": "Settings could not be saved. Check permissions or try again. (｡•́︿•̀｡)",
        "settings_save_failed_exit_prompt": "General settings could not be saved. Quit without saving changes? Choose No to return and retry. (｡•ㅅ•｡)",
        "worker.status.scan_cancelled": "Scan cancelled (・ω・)",
        "controller.window_title": "CloudHime",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI Translate",
        "controller.button.fullscreen": "Full Screen",
        "controller.button.region": "Select Area",
        "controller.button.stop": "Stop",
        "controller.button.auto_scan": "Auto Scan",
        "controller.button.auto_wait": "Pause · {seconds}s",
        "controller.button.auto_busy": "Pause · Translating",
        "controller.button.auto_resume": "Resume Auto Scan",
        "controller.tooltip.auto_scan": "Scan at selected interval. Click again to pause and keep subtitles; Stop clears them. (◍•ᴗ•◍)",
        "controller.tooltip.auto_resume": "Resume scanning at interval, keeping current subtitles while waiting. (´▽｀)",
        "controller.status.auto_paused": "Auto scan paused. Take your time reading; Resume Auto Scan continues translation. (*´∀`)",
        "selection.hint.drag": "Drag around text to read · Esc cancels and keeps previous mode & area (・ω・)ノ",
        "selection.hint.size": "{width} × {height} · Release mouse to confirm this area! (๑•̀ㅂ•́)و",
        "selection.hint.too_small": "{width} × {height} · Area is too small; please select at least 20 × 20. (｡•ㅅ•｡)",
        "controller.status.selection_cancelled": "Selection cancelled. Your previous mode and area are kept intact! (´▽｀)",
        "controller.button.random_scan_prefix": "Random",
        "controller.button.now": "Translate Now",
        "controller.button.wait": "Wait {seconds}s",
        "controller.button.translating": "Translating…",
        "controller.hint.fullscreen": "First time? Select a small area to try! Full screen reads the entire screen. (◍•ᴗ•◍)",
        "controller.hint.region": "Area selected! Translate now to see results, or click Select Area to reselect. (・ω・)ノ",
        "controller.tooltip.region": "Drag to select translation area; Esc cancels selection (・ω・)ノ",
        "controller.tooltip.minimize": "Minimize",
        "controller.tooltip.stop": "Stop translation and clear subtitles (Esc) (・∀・)",
        "controller.tooltip.interval": "Auto-scan interval; actual timing varies within the random range. (・ω・)",
        "controller.scan_interval.approx": "About {seconds}s",
        "controller.tooltip.settings": "Settings",
        "controller.tooltip.hotkey": "Shortcut: {shortcut}",
        "controller.tooltip.close": "Close",
        "controller.status.ready": "Ready to turn foreign screen text into clear translations for you! (◍•ᴗ•◍)",
        "controller.status.ai_model_ready": "Current AI model: {model}",
        "controller.status.auto_scanning": "{prefix} auto-scanning... (・ω・)",
        "controller.status.auto_stopped": "⏸ Auto scan stopped (・∀・)",
        "controller.status.shutting_down": "Waiting for background work to finish before closing… (｡•ㅅ•｡)",
        "controller.status.immediate_scanning": "⚡ Scanning now... (๑•̀ㅂ•́)و",
        "controller.status.need_api_key": "Please enter your Google API key in Settings first. (｡•ㅅ•｡)",
        "controller.status.need_region": "Please select a scan area first. (・ω・)ノ",
        "controller.status.region_ready": "Area ready: {size}. You can start translating! (๑•̀ㅂ•́)و",
        "controller.status.capture_running": "🖼 Screenshot translation running... (・ω・)",
        "controller.status.cold_down": "⚡ Cooling down for a moment... (´ω｀*)",
        "controller.status.ai_model_auto_switch": "AI model auto switch: {old_label} -> {new_label} (・ω・)",
        "controller.status.ai_model_full_switch": "{current} is full; next run will switch to {backup}. (｡•ㅅ•｡)",
        "controller.status.ai_model_full_google": "{current} is full {limit}/{limit}; switching to Google for now. (o´ω`o)",
        "controller.mode.fullscreen": "🖥 Mode: Full screen",
        "controller.mode.relief": "🧩 Mode: Relief",
        "controller.mode.screenshot": "🖼 Mode: Screenshot",
        "controller.mode.bubble": "💬 Mode: Bubble",
        "controller.mode.scan_fullscreen": "Full screen",
        "controller.mode.scan_region": "Region",
        "worker.status.threshold_tuning": "🔎 Fine-tuning threshold... (｡•ㅅ•｡)",
        "worker.status.sentence_recheck": "🧠 Rechecking sentence completeness... (*´∀`)",
        "worker.status.no_ocr_backend": "No recognition engine available. Open Settings → Capture & display to check or install an OCR engine. (｡•ㅅ•｡)",
        "worker.status.windows_ocr_unavailable": "Windows OCR language support is unavailable. Install an OCR language in Windows Settings > Time & language > Language & region, or enable another OCR backend in CloudHime. (｡•ㅅ•｡)",
        "worker.status.capture_failed": "Could not read the screen. Switch to the window you want to translate and try again ({error}). (｡•́︿•̀｡)",
        "worker.status.screenshot_requires_ai": "No text extracted for translation. Choose an image-capable engine or select clearer text. (｡•ㅅ•｡)",
        "worker.status.screenshot_translating": "🖼 Screenshot translation running... (・ω・)",
        "worker.status.screenshot_failed": "Screenshot translation did not finish. Check engine settings and connection, then retry ({error}). (｡•́︿•̀｡)",
        "worker.status.screenshot_empty": "The engine returned no translation. Check settings or select the screen area again. (｡•ㅅ•｡)",
        "worker.status.screen_static": "♻️ Frame static (・∀・)",
        "worker.status.screenshot_done": "✅ Screenshot translation complete! ヽ(・∀・)ﾉ",
        "worker.status.smart_crop": "🧭 Smart crop analyzing... (・ω・)",
        "worker.status.scanning_translating": "🔍 Scanning and translating... (๑•̀ㅂ•́)و",
        "worker.status.recognition_error": "❌ Recognition error (｡•́︿•̀｡)",
        "worker.status.crop_retry_full": "🧭 Too few smart-crop results; retrying full screen... (｡•ㅅ•｡)",
        "worker.status.crop_retry_rotate": "No text found in selected area; retrying with rotation... (・ω・)",
        "worker.status.crop_retry_zoom": "No text found in selected area. Try a larger region or a different angle. (｡•ㅅ•｡)",
        "worker.status.comic_retry": "📚 Retrying comic-page slicing... (*´∀`)",
        "worker.status.best_threshold": "✨ Best threshold selected: {threshold} (๑•̀ㅂ•́)و",
        "worker.status.ai_big_translation": "🧠 AI large-image translation... (・ω・)",
        "worker.status.google_translation": "🌐 Google translating... (・ω・)",
        "worker.status.local_gemma_translation": "🧠 Local Gemma translating... (๑•̀ㅂ•́)و",
        "worker.status.local_gemma_batch": "🧠 Local Gemma filling in {count} segments... (｡•ㅅ•｡)",
        "worker.status.local_gemma_progress": "🧠 Local Gemma {index}/{count} (・ω・)",
        "worker.status.exact_frame_cache": "♻️ Same screen as before (cached) ( ´ ▽ ` )ﾉ",
        "worker.status.batch_translate": "{icon} {prefix} Backfilling {count} segments... (｡•ㅅ•｡)",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total} (・ω・)",
        "worker.status.translation_done": "✅ Translation complete! ヽ(・∀・)ﾉ",
        "worker.status.translation_failed": "Translation did not finish. Check engine settings and connection, then try again. (｡•́︿•̀｡)",
        "worker.status.translation_incomplete": "Some text was kept in original language as translation did not finish. Check the engine and try again. (｡•ㅅ•｡)",
        "worker.status.translation_rate_limited": "Google Translate is rate limited. Wait and try again, or switch translation engines. (´・ω・)",
        "worker.status.no_text": "No readable text found. Try selecting an area with clearer text. (｡•ㅅ•｡)",
        "controller.hint.region_empty": "Select a small area of clear text, then click Translate now! (・ω・)ノ",
        "controller.engine.google": "Google Translate",
        "controller.engine.local_gemma": "Local Gemma",
        "controller.engine.online_gemma": "Online Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "Internet required",
        "controller.engine.state.configured": "API key configured; connection unverified (・ω・)",
        "controller.engine.state.setup": "API key needed (｡•ㅅ•｡)",
        "controller.engine.state.preparing": "Preparing model... (◍•ᴗ•◍)",
        "controller.engine.state.ready": "Model ready! (๑•̀ㅂ•́)و✧",
        "controller.engine.state.failed": "Model needs attention (｡•́︿•̀｡)",
        "controller.engine.state.unverified": "Model not ready (｡•ㅅ•｡)",
        "controller.engine.pending": "{name} setup pending (｡•ㅅ•｡)",
        "controller.engine.change": "Change engine",
        "controller.engine.settings_description": "Open engine settings to review requirements and data destinations. (・ω・)ノ",
        "controller.engine.data.google": "Recognized text goes to Google. Cloud OCR also sends images when enabled. (o´ω`o)",
        "controller.engine.data.local_gemma": "The local model processes content on device. Cloud OCR, remote endpoints, or online fallbacks may still send content. (o´ω`o)",
        "controller.engine.data.online_gemma": "Text or images go to Google. Other fallbacks depend on engine settings. (o´ω`o)",
        "controller.engine.data.luna": "Text or images go to OpenAI. Other fallbacks depend on engine settings. (o´ω`o)",
    },
    "ja": {
        "settings_title": "設定",
        "settings_subtitle": "翻訳、OCR、外観、スキャン動作を管理します。 (・ω・)ノ",
        "settings_close": "閉じる",
        "settings_theme_mode": "テーマ",
        "settings_ui_language": "表示言語",
        "settings_knowledge_placeholder": "ゲームまたは漫画のタイトルを入力 (・ω・)",
        "settings_knowledge_research": "この作品を調べる (๑•̀ㅂ•́)و",
        "settings_knowledge_update": "ナレッジを更新 (´▽｀)",
        "settings_knowledge_building": "調査中… (｡•ㅅ•｡)",
        "settings_knowledge_progress": "調査中… {percent}% (｡•ㅅ•｡)",
        "settings_knowledge_ready": "✓ ナレッジパックを作成しました！ (๑•̀ㅂ•́)و✧",
        "settings_knowledge_missing": "未作成 (・ω・)",
        "settings_knowledge_unavailable": "調査機能はまだ設定されていません (｡•́︿•̀｡)",
        "settings_knowledge_failed": "作成に失敗しましたが、他の設定は引き続き利用できます (｡•ㅅ•｡)",
        "settings_knowledge_model_hint": "調査・抽出に使うモデルを選択 (・ω・)",
        "settings_knowledge_sources_placeholder": "任意：公開ソースの URL を空白区切りで入力。空欄の場合は自動検索します (・ω・)",
        "settings_knowledge_review_title": "調査候補を確認 (・ω・)",
        "settings_knowledge_review_message": "{title}\n\n{sources} 件のソースを読み込み、{entries} 件の項目を抽出しました。矛盾する {conflicts} 件と、信頼度が低い、または無効な {rejected} 件は除外しました。この候補を未有効のナレッジパックとして保存しますか？ (◍•ᴗ•◍)",
        "settings_knowledge_not_saved": "候補は保存されませんでした (・ω・)",
        "settings_save_failed": "設定を保存できませんでした。権限を確認して再試行してください (｡•́︿•̀｡)",
        "settings_save_failed_exit_prompt": "一般設定を保存できませんでした。未保存の変更を破棄して終了しますか？「いいえ」で戻って再試行できます (｡•ㅅ•｡)",
        "worker.status.scan_cancelled": "スキャンをキャンセルしました (・ω・)",
        "controller.window_title": "CloudHime クラウド姫",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI 翻訳",
        "controller.button.fullscreen": "全画面",
        "controller.button.region": "範囲選択",
        "controller.button.stop": "停止",
        "controller.button.auto_scan": "自動スキャン",
        "controller.button.auto_wait": "一時停止・{seconds} 秒",
        "controller.button.auto_busy": "一時停止・翻訳中",
        "controller.button.auto_resume": "自動スキャン再開",
        "controller.tooltip.auto_scan": "選んだ間隔でスキャンします。もう一度押すと字幕を残して一時停止し、「停止」で字幕を消去します (◍•ᴗ•◍)",
        "controller.tooltip.auto_resume": "現在の字幕を残し、設定した間隔でスキャンを再開します (´▽｀)",
        "controller.status.auto_paused": "自動スキャンを一時停止しました。字幕をゆっくり読んでから「自動スキャン再開」を押してくださいね (*´∀`)",
        "selection.hint.drag": "読みたい文字をドラッグで囲む・Esc で元のモードと範囲を保持します (・ω・)ノ",
        "selection.hint.size": "{width} × {height}・マウスを離して範囲を決定します！ (๑•̀ㅂ•́)و",
        "selection.hint.too_small": "{width} × {height}・範囲が小さすぎます。20 × 20 以上に広げてくださいね (｡•ㅅ•｡)",
        "controller.status.selection_cancelled": "選択を取り消しました。元のモードと範囲を保持します (´▽｀)",
        "controller.button.random_scan_prefix": "ランダム",
        "controller.button.now": "今すぐ翻訳",
        "controller.button.wait": "あと {seconds} 秒",
        "controller.button.translating": "翻訳中…",
        "controller.hint.fullscreen": "初めてですか？まずは「範囲選択」で小さなエリアから試してみてね。全画面は画面全体を読み取ります (◍•ᴗ•◍)",
        "controller.hint.region": "範囲を選択しました！「今すぐ翻訳」で確認するか、「範囲選択」で選び直せます (・ω・)ノ",
        "controller.tooltip.region": "ドラッグで翻訳範囲を選択・Esc で選択をキャンセル (・ω・)ノ",
        "controller.tooltip.minimize": "最小化",
        "controller.tooltip.stop": "翻訳を停止して字幕を消去 (Esc) (・∀・)",
        "controller.tooltip.interval": "自動スキャンの間隔・実際の時間はランダム範囲内で変動します (・ω・)",
        "controller.scan_interval.approx": "約 {seconds} 秒",
        "controller.tooltip.settings": "設定",
        "controller.tooltip.hotkey": "ショートカット：{shortcut}",
        "controller.tooltip.close": "閉じる",
        "controller.status.ready": "画面の外国語を、分かりやすい言葉にお届けします～ (◍•ᴗ•◍)",
        "controller.status.ai_model_ready": "現在の AI モデル：{model}",
        "controller.status.auto_scanning": "{prefix} 自動スキャン中… (・ω・)",
        "controller.status.auto_stopped": "⏸ 自動スキャン停止中 (・∀・)",
        "controller.status.shutting_down": "バックグラウンド処理の終了を待って閉じています… (｡•ㅅ•｡)",
        "controller.status.immediate_scanning": "⚡ スキャン中... (๑•̀ㅂ•́)و",
        "controller.status.need_api_key": "先に設定で Google API キーを入力してくださいね (｡•ㅅ•｡)",
        "controller.status.need_region": "先にスキャン範囲を設定してくださいね (・ω・)ノ",
        "controller.status.region_ready": "範囲を決めました：{size}。翻訳を開始できます！ (๑•̀ㅂ•́)و",
        "controller.status.capture_running": "🖼 スクリーンショットを翻訳中... (・ω・)",
        "controller.status.cold_down": "⚡ クールダウン中…少しお待ちくださいね (´ω｀*)",
        "controller.status.ai_model_auto_switch": "AI モデルを自動切替：{old_label} → {new_label} (・ω・)",
        "controller.status.ai_model_full_switch": "{current} は上限に達しました。次回は {backup} に切り替えますね (｡•ㅅ•｡)",
        "controller.status.ai_model_full_google": "{current} は上限 {limit}/{limit} に達しました。Google に切り替えますね (o´ω`o)",
        "controller.mode.fullscreen": "🖥 モード：全画面",
        "controller.mode.relief": "🧩 モード：浮き彫り",
        "controller.mode.screenshot": "🖼 モード：スクリーンショット",
        "controller.mode.bubble": "💬 モード：吹き出し",
        "controller.mode.scan_fullscreen": "全画面",
        "controller.mode.scan_region": "範囲",
        "worker.status.threshold_tuning": "🔎 しきい値を微調整中... (｡•ㅅ•｡)",
        "worker.status.sentence_recheck": "🧠 文の完全性を再確認中... (*´∀`)",
        "worker.status.no_ocr_backend": "認識エンジンがありません。設定 → キャプチャと表示で OCR エンジンを確認・インストールしてくださいね (｡•ㅅ•｡)",
        "worker.status.windows_ocr_unavailable": "Windows OCR の言語機能を利用できません。Windows の「時刻と言語 → 言語と地域」で OCR 言語を追加するか、CloudHime で別の OCR バックエンドを有効にしてくださいね (｡•ㅅ•｡)",
        "worker.status.capture_failed": "画面を読み取れませんでした。翻訳するウィンドウに戻って再試行してくださいね（{error}） (｡•́︿•̀｡)",
        "worker.status.screenshot_requires_ai": "翻訳する文字をまだ取得できていません。画像対応エンジンを選ぶか、鮮明な文字を選択してくださいね (｡•ㅅ•｡)",
        "worker.status.screenshot_translating": "🖼 スクリーンショットを翻訳中... (・ω・)",
        "worker.status.screenshot_failed": "画像の翻訳が完了しませんでした。エンジン設定と接続を確認して再試行してくださいね（{error}） (｡•́︿•̀｡)",
        "worker.status.screenshot_empty": "エンジンから翻訳が返されませんでした。設定を確認するか、画面の範囲を選び直してくださいね (｡•ㅅ•｡)",
        "worker.status.screen_static": "♻️ 画面に変化はありません (・∀・)",
        "worker.status.screenshot_done": "✅ スクリーンショットの翻訳が完了しました！ ヽ(・∀・)ﾉ",
        "worker.status.smart_crop": "🧭 スマート切り抜きを解析中... (・ω・)",
        "worker.status.scanning_translating": "🔍 スキャンして翻訳中... (๑•̀ㅂ•́)و",
        "worker.status.recognition_error": "❌ 認識エラー (｡•́︿•̀｡)",
        "worker.status.crop_retry_full": "🧭 スマート切り抜きの結果が少ないため、画面全体で再試行します... (｡•ㅅ•｡)",
        "worker.status.crop_retry_rotate": "選択範囲に文字が見つかりません。回転して再試行しています... (・ω・)",
        "worker.status.crop_retry_zoom": "選択範囲に文字が見つかりません。範囲を広げるか、角度を変えてみてくださいね (｡•ㅅ•｡)",
        "worker.status.comic_retry": "📚 漫画ページの分割を再試行中... (*´∀`)",
        "worker.status.best_threshold": "✨ 最適なしきい値を選択しました：{threshold} (๑•̀ㅂ•́)و",
        "worker.status.ai_big_translation": "🧠 AI で大きな画像を翻訳中... (・ω・)",
        "worker.status.google_translation": "🌐 Google で翻訳中... (・ω・)",
        "worker.status.local_gemma_translation": "🧠 ローカル Gemma で翻訳中... (๑•̀ㅂ•́)و",
        "worker.status.local_gemma_batch": "🧠 ローカル Gemma が {count} 件を補完中... (｡•ㅅ•｡)",
        "worker.status.local_gemma_progress": "🧠 ローカル Gemma {index}/{count} (・ω・)",
        "worker.status.exact_frame_cache": "♻️ 前回と同じ画面（キャッシュ使用） ( ´ ▽ ` )ﾉ",
        "worker.status.batch_translate": "{icon} {prefix} {count} 件をまとめて翻訳中... (｡•ㅅ•｡)",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total} (・ω・)",
        "worker.status.translation_done": "✅ 翻訳が完了しました！ ヽ(・∀・)ﾉ",
        "worker.status.translation_failed": "翻訳が完了しませんでした。エンジン設定と接続を確認して再試行してくださいね (｡•́︿•̀｡)",
        "worker.status.translation_incomplete": "一部のテキストは原文のままです。翻訳エンジンを確認して再試行してくださいね (｡•ㅅ•｡)",
        "worker.status.translation_rate_limited": "Google 翻訳は現在利用制限中です。時間をおいて再試行するか、別の翻訳エンジンに切り替えてくださいね (´・ω・)",
        "worker.status.no_text": "認識できる文字がありません。鮮明な文字の範囲を選択してみてくださいね (｡•ㅅ•｡)",
        "controller.hint.region_empty": "読みやすい外国語の文字を囲み、「今すぐ翻訳」を押してくださいね！ (・ω・)ノ",
        "controller.engine.google": "Google 翻訳",
        "controller.engine.local_gemma": "ローカル Gemma",
        "controller.engine.online_gemma": "オンライン Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "ネット接続が必要",
        "controller.engine.state.configured": "キー設定済み・接続未確認 (・ω・)",
        "controller.engine.state.setup": "API キーが必要です (｡•ㅅ•｡)",
        "controller.engine.state.preparing": "モデル準備中… (◍•ᴗ•◍)",
        "controller.engine.state.ready": "モデル準備完了！ (๑•̀ㅂ•́)و✧",
        "controller.engine.state.failed": "モデルの確認が必要です (｡•́︿•̀｡)",
        "controller.engine.state.unverified": "モデル未準備 (｡•ㅅ•｡)",
        "controller.engine.pending": "{name} の設定待ちです (｡•ㅅ•｡)",
        "controller.engine.change": "エンジン変更",
        "controller.engine.settings_description": "翻訳エンジンの設定で必要条件とデータの送信先を確認します (・ω・)ノ",
        "controller.engine.data.google": "認識した文字を Google に送信します。クラウド OCR 有効時は画像も送信します (o´ω`o)",
        "controller.engine.data.local_gemma": "ローカルモデルで処理します。クラウド OCR、リモート接続、オンラインの代替処理では内容を送信する場合があります (o´ω`o)",
        "controller.engine.data.online_gemma": "文字や画像を Google に送信します。他の代替処理はエンジン設定によります (o´ω`o)",
        "controller.engine.data.luna": "文字や画像を OpenAI に送信します。他の代替処理はエンジン設定によります (o´ω`o)",
    },
}


def normalize_ui_language(language: Any, fallback: str = DEFAULT_UI_LANGUAGE) -> str:
    candidate = str(language or "").strip()
    if not candidate:
        return fallback
    normalized = _LANGUAGE_ALIASES.get(candidate.lower(), candidate)
    if normalized in SUPPORTED_UI_LANGUAGES:
        return normalized
    if normalized.lower().startswith("zh"):
        return "zh-TW"
    if normalized.lower().startswith("en"):
        return "en"
    if normalized.lower().startswith("ja"):
        return "ja"
    return fallback


def get_translation_target_lang(ui_language: Any, fallback: str = DEFAULT_UI_LANGUAGE) -> str:
    normalized = normalize_ui_language(ui_language, fallback=fallback)
    # 如果UI是英文，翻譯目標設為英文
    if normalized == "en":
        return "en"
    if normalized == "ja":
        return "ja"
    # 如果UI是中文，翻譯目標設為繁體中文
    elif normalized == "zh-TW":
        return "zh-TW"
    return "zh-TW"


def fallback_text(value: Any, fallback: Any = "") -> str:
    text = str(value or "").strip()
    if text:
        return text
    return str(fallback or "")


def tr(key: str, language: Any = DEFAULT_UI_LANGUAGE, fallback: str | None = None, **params: Any) -> str:
    normalized = normalize_ui_language(language)
    catalog = _TRANSLATIONS.get(normalized, {})
    default_catalog = _TRANSLATIONS.get(DEFAULT_UI_LANGUAGE, {})
    text = catalog.get(key) or default_catalog.get(key) or fallback or key
    if params:
        try:
            text = text.format(**params)
        except Exception:
            pass
    return text
