from __future__ import annotations

from typing import Any


DEFAULT_UI_LANGUAGE = "en"
SUPPORTED_UI_LANGUAGES = ("en", "zh-TW", "ja")

_LANGUAGE_ALIASES = {
    "zh": "zh-TW",
    "zh-hant": "zh-TW",
    "zh-tw": "zh-TW",
    "zh-hk": "zh-TW",
    "zh-mo": "zh-TW",
    "en": "en",
    "en-us": "en",
    "en-gb": "en",
    "ja": "ja",
    "ja-jp": "ja",
    "jp": "ja",
}

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "zh-TW": {
        "settings_title": "設定",
        "settings_subtitle": "管理翻譯、OCR、外觀和掃描行為。",
        "settings_close": "關閉",
        "settings_theme_mode": "主題",
        "settings_ui_language": "介面語言",
        "settings_knowledge_placeholder": "輸入遊戲或漫畫名稱",
        "settings_knowledge_research": "幫我查這個作品",
        "settings_knowledge_update": "更新小本本",
        "settings_knowledge_building": "正在查資料…",
        "settings_knowledge_progress": "正在查資料… {percent}%",
        "settings_knowledge_ready": "✓ 小本本已建立",
        "settings_knowledge_missing": "尚未建立",
        "settings_knowledge_unavailable": "研究功能尚未設定",
        "settings_knowledge_failed": "建立失敗，其他設定仍可使用",
        "settings_knowledge_model_hint": "選擇研究萃取模型",
        "settings_knowledge_sources_placeholder": "選填：公開來源網址，以空白分隔；留空則自動搜尋",
        "settings_knowledge_review_title": "確認研究候選包",
        "settings_knowledge_review_message": "{title}\n\n已讀取 {sources} 個來源，整理出 {entries} 筆條目；另有 {conflicts} 筆衝突、{rejected} 筆低信心或無效資料未採用。要將這份候選資料存成未啟用的小本本嗎？",
        "settings_knowledge_not_saved": "候選資料未儲存",
        "settings_save_failed": "設定無法儲存",
        "settings_save_failed_exit_prompt": "一般設定無法儲存。要放棄尚未儲存的變更並結束嗎？選「否」可返回並重試。",
        "worker.status.scan_cancelled": "掃描已取消",
        "controller.window_title": "CloudHime",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI 翻譯",
        "controller.button.fullscreen": "全螢幕",
        "controller.button.region": "框選區域",
        "controller.button.stop": "停止",
        "controller.button.auto_scan": "自動掃描",
        "controller.button.auto_wait": "暫停・{seconds} 秒",
        "controller.button.auto_busy": "暫停・翻譯中",
        "controller.button.auto_resume": "繼續自動掃描",
        "controller.tooltip.auto_scan": "依選定間隔掃描；再按可暫停並保留字幕，「停止」會清除字幕",
        "controller.tooltip.auto_resume": "繼續依間隔掃描；等待期間保留目前字幕",
        "controller.status.auto_paused": "自動掃描已暫停，字幕留著慢慢讀；按「繼續自動掃描」接著翻譯。",
        "selection.hint.drag": "拖曳框住想讀的文字・Esc 取消，保留原模式與範圍",
        "selection.hint.size": "{width} × {height}・放開滑鼠，收好這個範圍",
        "selection.hint.too_small": "{width} × {height}・範圍太小，請拉到至少 20 × 20",
        "controller.status.selection_cancelled": "已取消框選，保留原本的模式與範圍。",
        "controller.button.random_scan_prefix": "隨機",
        "controller.button.now": "立即翻譯",
        "controller.button.wait": "等待 {seconds} 秒",
        "controller.button.translating": "翻譯中…",
        "controller.hint.fullscreen": "第一次使用？先選「框選區域」試一小段文字。全螢幕模式會讀取整個畫面。",
        "controller.hint.region": "範圍已選好，按「立即翻譯」看結果；再按「框選區域」可重新選取。",
        "controller.tooltip.region": "拖曳框選翻譯範圍；Esc 取消框選",
        "controller.tooltip.minimize": "最小化",
        "controller.tooltip.stop": "停止翻譯並清除字幕（Esc）",
        "controller.tooltip.interval": "自動掃描間隔；實際時間會依隨機範圍調整",
        "controller.scan_interval.approx": "約 {seconds} 秒",
        "controller.tooltip.settings": "設定",
        "controller.tooltip.hotkey": "快捷鍵：{shortcut}",
        "controller.tooltip.close": "關閉",
        "controller.status.ready": "把畫面上的外語，翻成看得懂的文字。",
        "controller.status.ai_model_ready": "AI 模型：{model}",
        "controller.status.auto_scanning": "{prefix} 自動掃描中",
        "controller.status.auto_stopped": "⏸ 自動已停止",
        "controller.status.shutting_down": "正在等待背景工作結束後關閉…",
        "controller.status.immediate_scanning": "⚡ 立即掃描中...",
        "controller.status.need_api_key": "請先輸入 Google API KEY",
        "controller.status.need_region": "請先設定框選區域",
        "controller.status.region_ready": "範圍收好了：{size}，可以開始翻譯。",
        "controller.status.capture_running": "🖼 截圖翻譯進行中...",
        "controller.status.cold_down": "⚡ 冷卻充電中...",
        "controller.status.ai_model_auto_switch": "AI 模型自動切換：{old_label} -> {new_label}",
        "controller.status.ai_model_full_switch": "{current} 已滿，下一次會自動切到 {backup}",
        "controller.status.ai_model_full_google": "{current} 已滿 {limit}/{limit}，先改用 Google",
        "controller.mode.fullscreen": "🖥 模式：全螢幕",
        "controller.mode.relief": "🧩 模式：浮雕",
        "controller.mode.screenshot": "🖼 模式：截圖",
        "controller.mode.bubble": "💬 模式：氣泡",
        "controller.mode.scan_fullscreen": "全螢幕",
        "controller.mode.scan_region": "區域",
        "worker.status.threshold_tuning": "🔎 局部微調閥值中...",
        "worker.status.sentence_recheck": "🧠 句子完整度複判中...",
        "worker.status.no_ocr_backend": "沒有可用的辨識引擎。請到設定 → 擷取與顯示，確認或安裝 OCR 引擎。",
        "worker.status.windows_ocr_unavailable": "Windows OCR 語言功能目前不可用。請在 Windows 設定的「時間與語言 → 語言與地區」安裝 OCR 語言，或在 CloudHime 啟用其他 OCR 後端。",
        "worker.status.capture_failed": "無法讀取畫面，請切回要翻譯的視窗再試（{error}）。",
        "worker.status.screenshot_requires_ai": "目前未取得可翻譯的文字。請選支援圖片的引擎，或框選更清楚的文字。",
        "worker.status.screenshot_translating": "🖼 截圖模式翻譯中...",
        "worker.status.screenshot_failed": "截圖翻譯未完成，請檢查引擎設定與連線後再試（{error}）。",
        "worker.status.screenshot_empty": "引擎沒有回傳翻譯，請檢查引擎設定或重新框選畫面再試。",
        "worker.status.screen_static": "♻️ 畫面靜止",
        "worker.status.screenshot_done": "✅ 截圖翻譯完成",
        "worker.status.smart_crop": "🧭 智慧裁切分析中...",
        "worker.status.scanning_translating": "🔍 掃描與翻譯中...",
        "worker.status.recognition_error": "❌ 辨識錯誤",
        "worker.status.crop_retry_full": "🧭 智慧裁切結果太少，改用全畫面重試...",
        "worker.status.crop_retry_rotate": "框選區域沒有掃到字，正在改用旋轉重試...",
        "worker.status.crop_retry_zoom": "框選區域沒有掃到文字，請框大一點或換個角度。",
        "worker.status.comic_retry": "📚 漫畫頁切片重試中...",
        "worker.status.best_threshold": "✨ 已選最佳閥值 {threshold}",
        "worker.status.ai_big_translation": "🧠 AI 大圖翻譯...",
        "worker.status.google_translation": "🌐 Google 翻譯中...",
        "worker.status.batch_translate": "{icon} {prefix} 批次補翻 {count} 段...",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total}",
        "worker.status.translation_done": "✅ 翻譯完成",
        "worker.status.translation_failed": "這次翻譯未完成。請檢查引擎設定與連線後再試。",
        "worker.status.translation_incomplete": "部分文字保留原文，翻譯未完成。請檢查翻譯引擎後重試。",
        "worker.status.translation_rate_limited": "Google 翻譯目前受到流量限制，請稍後重試或切換翻譯引擎。",
        "worker.status.no_text": "沒找到可辨識的文字，試著框選清楚的文字區域。",
        "controller.hint.region_empty": "先框住一小段清楚的外文，再按「立即翻譯」。",
        "controller.engine.google": "Google 翻譯",
        "controller.engine.local_gemma": "本機 Gemma",
        "controller.engine.online_gemma": "線上 Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "需網路",
        "controller.engine.state.configured": "金鑰已設定，連線未驗證",
        "controller.engine.state.setup": "需要設定金鑰",
        "controller.engine.state.preparing": "模型準備中",
        "controller.engine.state.ready": "模型已就緒",
        "controller.engine.state.failed": "模型需要處理",
        "controller.engine.state.unverified": "模型尚未就緒",
        "controller.engine.pending": "{name} 尚待設定",
        "controller.engine.change": "切換引擎",
        "controller.engine.settings_description": "開啟翻譯引擎設定，查看需求與資料去向",
        "controller.engine.data.google": "辨識文字會送往 Google；雲端 OCR 啟用時也會送出畫面。",
        "controller.engine.data.local_gemma": "本機模型處理內容；雲端 OCR、遠端端點或線上備援仍可能送出內容。",
        "controller.engine.data.online_gemma": "文字或畫面會送往 Google；其他備援依引擎設定。",
        "controller.engine.data.luna": "文字或畫面會送往 OpenAI；其他備援依引擎設定。",
    },
    "en": {
        "settings_title": "Settings",
        "settings_subtitle": "Manage translation, OCR, appearance, and scan behavior in one place.",
        "settings_close": "Close",
        "settings_theme_mode": "Theme",
        "settings_ui_language": "UI Language",
        "settings_knowledge_placeholder": "Enter game or manga title",
        "settings_knowledge_research": "Research this work",
        "settings_knowledge_update": "Update knowledge",
        "settings_knowledge_building": "Researching…",
        "settings_knowledge_progress": "Researching… {percent}%",
        "settings_knowledge_ready": "✓ Knowledge pack ready",
        "settings_knowledge_missing": "Not created yet",
        "settings_knowledge_unavailable": "Research is not configured yet",
        "settings_knowledge_failed": "Build failed; other settings are still available",
        "settings_knowledge_model_hint": "Choose the research extraction model",
        "settings_knowledge_sources_placeholder": "Optional public URLs separated by spaces; leave blank to search",
        "settings_knowledge_review_title": "Confirm research candidate",
        "settings_knowledge_review_message": "{title}\n\nRead {sources} sources and extracted {entries} entries; {conflicts} conflicts and {rejected} low-confidence or invalid items were excluded. Save this candidate as a non-active knowledge pack?",
        "settings_knowledge_not_saved": "Candidate was not saved",
        "settings_save_failed": "Settings could not be saved",
        "settings_save_failed_exit_prompt": "General settings could not be saved. Quit without saving these changes? Choose No to return and retry.",
        "worker.status.scan_cancelled": "Scan cancelled",
        "controller.window_title": "CloudHime",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI Translate",
        "controller.button.fullscreen": "Full Screen",
        "controller.button.region": "Select area",
        "controller.button.stop": "Stop",
        "controller.button.auto_scan": "Auto Scan",
        "controller.button.auto_wait": "Pause · {seconds}s",
        "controller.button.auto_busy": "Pause · Translating",
        "controller.button.auto_resume": "Resume Auto Scan",
        "controller.tooltip.auto_scan": "Scan at the selected interval. Click again to pause and keep captions; Stop clears them",
        "controller.tooltip.auto_resume": "Resume scanning at the interval, keeping current captions while waiting",
        "controller.status.auto_paused": "Auto scan paused. Take your time reading; Resume Auto Scan continues translation.",
        "selection.hint.drag": "Drag around the text you want to read · Esc keeps your previous mode and area",
        "selection.hint.size": "{width} × {height} · Release to keep this area",
        "selection.hint.too_small": "{width} × {height} · Select at least 20 × 20",
        "controller.status.selection_cancelled": "Selection cancelled. Your previous mode and area are kept.",
        "controller.button.random_scan_prefix": "Random",
        "controller.button.now": "Translate Now",
        "controller.button.wait": "Wait {seconds}s",
        "controller.button.translating": "Translating…",
        "controller.hint.fullscreen": "First time? Select a small area to try. Full screen reads the entire screen.",
        "controller.hint.region": "Area selected. Translate now to see the result, or select another area.",
        "controller.tooltip.region": "Drag to select a translation area; Esc cancels selection",
        "controller.tooltip.minimize": "Minimize",
        "controller.tooltip.stop": "Stop translation and clear subtitles (Esc)",
        "controller.tooltip.interval": "Auto-scan interval; actual timing varies within the random range",
        "controller.scan_interval.approx": "About {seconds}s",
        "controller.tooltip.settings": "Settings",
        "controller.tooltip.hotkey": "Shortcut: {shortcut}",
        "controller.tooltip.close": "Close",
        "controller.status.ready": "Read the screen's foreign text in your language.",
        "controller.status.ai_model_ready": "AI model: {model}",
        "controller.status.auto_scanning": "{prefix} auto-scanning",
        "controller.status.auto_stopped": "⏸ Auto stopped",
        "controller.status.shutting_down": "Waiting for background work to finish before closing…",
        "controller.status.immediate_scanning": "⚡ Scanning now...",
        "controller.status.need_api_key": "Please enter your Google API key first",
        "controller.status.need_region": "Please set a scan region first",
        "controller.status.region_ready": "Area ready: {size}. You can start translating.",
        "controller.status.capture_running": "🖼 Screenshot translation running...",
        "controller.status.cold_down": "⚡ Cooling down...",
        "controller.status.ai_model_auto_switch": "AI model auto switch: {old_label} -> {new_label}",
        "controller.status.ai_model_full_switch": "{current} is full; next run will switch to {backup}",
        "controller.status.ai_model_full_google": "{current} is full {limit}/{limit}; using Google for now",
        "controller.mode.fullscreen": "🖥 Mode: Full screen",
        "controller.mode.relief": "🧩 Mode: Relief",
        "controller.mode.screenshot": "🖼 Mode: Screenshot",
        "controller.mode.bubble": "💬 Mode: Bubble",
        "controller.mode.scan_fullscreen": "Full screen",
        "controller.mode.scan_region": "Region",
        "worker.status.threshold_tuning": "🔎 Fine-tuning threshold...",
        "worker.status.sentence_recheck": "🧠 Rechecking sentence completeness...",
        "worker.status.no_ocr_backend": "No recognition engine is available. Open Settings → Capture & display to check or install an OCR engine.",
        "worker.status.windows_ocr_unavailable": "Windows OCR language support is unavailable. Install an OCR language in Windows Settings > Time & language > Language & region, or enable another OCR backend in CloudHime.",
        "worker.status.capture_failed": "Could not read the screen. Switch to the window you want to translate and try again ({error}).",
        "worker.status.screenshot_requires_ai": "No text has been extracted for translation. Choose an image-capable engine or select clearer text.",
        "worker.status.screenshot_translating": "🖼 Screenshot translation running...",
        "worker.status.screenshot_failed": "Screenshot translation did not finish. Check your engine settings and connection, then retry ({error}).",
        "worker.status.screenshot_empty": "The engine returned no translation. Check its settings or select the screen area again.",
        "worker.status.screen_static": "♻️ Frame static",
        "worker.status.screenshot_done": "✅ Screenshot translation complete",
        "worker.status.smart_crop": "🧭 Smart crop analyzing...",
        "worker.status.scanning_translating": "🔍 Scanning and translating...",
        "worker.status.recognition_error": "❌ Recognition error",
        "worker.status.crop_retry_full": "🧭 Too few smart-crop results; retrying full screen...",
        "worker.status.crop_retry_rotate": "No text found in the selected area; retrying with rotation...",
        "worker.status.crop_retry_zoom": "No text found in the selected area. Try a larger region or a different angle.",
        "worker.status.comic_retry": "📚 Retrying comic-page slicing...",
        "worker.status.best_threshold": "✨ Best threshold selected: {threshold}",
        "worker.status.ai_big_translation": "🧠 AI large-image translation...",
        "worker.status.google_translation": "🌐 Google translating...",
        "worker.status.batch_translate": "{icon} {prefix} Backfilling {count} segments...",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total}",
        "worker.status.translation_done": "✅ Translation complete",
        "worker.status.translation_failed": "Translation did not finish. Check your engine settings and connection, then try again.",
        "worker.status.translation_incomplete": "Some text was kept in the original language because translation did not finish. Check the engine and try again.",
        "worker.status.translation_rate_limited": "Google Translate is rate limited. Wait and try again, or switch translation engines.",
        "worker.status.no_text": "No readable text found. Try selecting an area with clearer text.",
        "controller.hint.region_empty": "Select a small area of clear text, then Translate now.",
        "controller.engine.google": "Google Translate",
        "controller.engine.local_gemma": "Local Gemma",
        "controller.engine.online_gemma": "Online Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "Internet required",
        "controller.engine.state.configured": "API key configured; connection unverified",
        "controller.engine.state.setup": "API key needed",
        "controller.engine.state.preparing": "Preparing model",
        "controller.engine.state.ready": "Model ready",
        "controller.engine.state.failed": "Model needs attention",
        "controller.engine.state.unverified": "Model not ready",
        "controller.engine.pending": "{name} setup pending",
        "controller.engine.change": "Change engine",
        "controller.engine.settings_description": "Open engine settings to review requirements and data destinations",
        "controller.engine.data.google": "Recognized text goes to Google. Cloud OCR also sends images when enabled.",
        "controller.engine.data.local_gemma": "The local model processes content. Cloud OCR, remote endpoints or online fallbacks may still send content.",
        "controller.engine.data.online_gemma": "Text or images go to Google. Other fallbacks depend on engine settings.",
        "controller.engine.data.luna": "Text or images go to OpenAI. Other fallbacks depend on engine settings.",
    },
    "ja": {
        "settings_title": "設定",
        "settings_subtitle": "翻訳、OCR、外観、スキャン動作を管理します。",
        "settings_close": "閉じる",
        "settings_theme_mode": "テーマ",
        "settings_ui_language": "表示言語",
        "settings_knowledge_placeholder": "ゲームまたは漫画のタイトルを入力",
        "settings_knowledge_research": "この作品を調べる",
        "settings_knowledge_update": "ナレッジを更新",
        "settings_knowledge_building": "調査中…",
        "settings_knowledge_progress": "調査中… {percent}%",
        "settings_knowledge_ready": "✓ ナレッジパックを作成しました",
        "settings_knowledge_missing": "未作成",
        "settings_knowledge_unavailable": "調査機能はまだ設定されていません",
        "settings_knowledge_failed": "作成に失敗しました。他の設定は引き続き利用できます",
        "settings_knowledge_model_hint": "調査・抽出に使うモデルを選択",
        "settings_knowledge_sources_placeholder": "任意：公開ソースの URL を空白区切りで入力。空欄の場合は自動検索します",
        "settings_knowledge_review_title": "調査候補を確認",
        "settings_knowledge_review_message": "{title}\n\n{sources} 件のソースを読み込み、{entries} 件の項目を抽出しました。矛盾する {conflicts} 件と、信頼度が低い、または無効な {rejected} 件は除外しました。この候補を未有効のナレッジパックとして保存しますか？",
        "settings_knowledge_not_saved": "候補は保存されませんでした",
        "settings_save_failed": "設定を保存できませんでした",
        "settings_save_failed_exit_prompt": "一般設定を保存できませんでした。未保存の変更を破棄して終了しますか？「いいえ」で戻って再試行できます。",
        "worker.status.scan_cancelled": "スキャンをキャンセルしました",
        "controller.window_title": "CloudHime",
        "controller.title": "CloudHime",
        "controller.placeholder.google_api_key": "Google API KEY",
        "controller.button.ai_translation": "AI 翻訳",
        "controller.button.fullscreen": "全画面",
        "controller.button.region": "範囲を選ぶ",
        "controller.button.stop": "停止",
        "controller.button.auto_scan": "自動スキャン",
        "controller.button.auto_wait": "一時停止・{seconds} 秒",
        "controller.button.auto_busy": "一時停止・翻訳中",
        "controller.button.auto_resume": "自動スキャンを再開",
        "controller.tooltip.auto_scan": "選んだ間隔でスキャンします。もう一度押すと字幕を残して一時停止し、「停止」で字幕を消します",
        "controller.tooltip.auto_resume": "現在の字幕を残し、設定した間隔でスキャンを再開します",
        "controller.status.auto_paused": "自動スキャンを一時停止しました。字幕をゆっくり読んでから「自動スキャンを再開」を押してください。",
        "selection.hint.drag": "読みたい文字をドラッグで囲む・Esc で元のモードと範囲を保持",
        "selection.hint.size": "{width} × {height}・マウスを離して範囲を決定",
        "selection.hint.too_small": "{width} × {height}・20 × 20 以上に広げてください",
        "controller.status.selection_cancelled": "選択を取り消しました。元のモードと範囲を保持します。",
        "controller.button.random_scan_prefix": "ランダム",
        "controller.button.now": "今すぐ翻訳",
        "controller.button.wait": "あと {seconds} 秒",
        "controller.button.translating": "翻訳中…",
        "controller.hint.fullscreen": "初めてですか？まず小さな範囲を選んで試しましょう。全画面では画面全体を読み取ります。",
        "controller.hint.region": "範囲を選択しました。「今すぐ翻訳」で結果を確認するか、範囲を選び直せます。",
        "controller.tooltip.region": "ドラッグで翻訳範囲を選択・Esc で選択をキャンセル",
        "controller.tooltip.minimize": "最小化",
        "controller.tooltip.stop": "翻訳を停止して字幕を消す（Esc）",
        "controller.tooltip.interval": "自動スキャンの間隔・実際の時間はランダム範囲内で変動します",
        "controller.scan_interval.approx": "約 {seconds} 秒",
        "controller.tooltip.settings": "設定",
        "controller.tooltip.hotkey": "ショートカット：{shortcut}",
        "controller.tooltip.close": "閉じる",
        "controller.status.ready": "画面の外国語を、読める言葉に。",
        "controller.status.ai_model_ready": "AI モデル：{model}",
        "controller.status.auto_scanning": "{prefix} 自動スキャン中",
        "controller.status.auto_stopped": "⏸ 自動スキャン停止中",
        "controller.status.shutting_down": "バックグラウンド処理の終了を待って閉じています…",
        "controller.status.immediate_scanning": "⚡ スキャン中...",
        "controller.status.need_api_key": "先に Google API キーを入力してください",
        "controller.status.need_region": "先にスキャン範囲を設定してください",
        "controller.status.region_ready": "範囲を決めました：{size}。翻訳を開始できます。",
        "controller.status.capture_running": "🖼 スクリーンショットを翻訳中...",
        "controller.status.cold_down": "⚡ クールダウン中...",
        "controller.status.ai_model_auto_switch": "AI モデルを自動切替：{old_label} → {new_label}",
        "controller.status.ai_model_full_switch": "{current} は上限に達しました。次回は {backup} に切り替えます",
        "controller.status.ai_model_full_google": "{current} は上限 {limit}/{limit} に達しました。Google に切り替えます",
        "controller.mode.fullscreen": "🖥 モード：全画面",
        "controller.mode.relief": "🧩 モード：浮き彫り",
        "controller.mode.screenshot": "🖼 モード：スクリーンショット",
        "controller.mode.bubble": "💬 モード：吹き出し",
        "controller.mode.scan_fullscreen": "全画面",
        "controller.mode.scan_region": "範囲",
        "worker.status.threshold_tuning": "🔎 しきい値を微調整中...",
        "worker.status.sentence_recheck": "🧠 文の完全性を再確認中...",
        "worker.status.no_ocr_backend": "認識エンジンがありません。設定 → キャプチャと表示で OCR エンジンを確認・インストールしてください。",
        "worker.status.windows_ocr_unavailable": "Windows OCR の言語機能を利用できません。Windows の「時刻と言語 → 言語と地域」で OCR 言語を追加するか、CloudHime で別の OCR バックエンドを有効にしてください。",
        "worker.status.capture_failed": "画面を読み取れませんでした。翻訳するウィンドウに戻って再試行してください（{error}）。",
        "worker.status.screenshot_requires_ai": "翻訳する文字をまだ取得できていません。画像対応エンジンを選ぶか、鮮明な文字を選択してください。",
        "worker.status.screenshot_translating": "🖼 スクリーンショットを翻訳中...",
        "worker.status.screenshot_failed": "画像の翻訳が完了しませんでした。エンジン設定と接続を確認して再試行してください（{error}）。",
        "worker.status.screenshot_empty": "エンジンから翻訳が返されませんでした。設定を確認するか、画面の範囲を選び直してください。",
        "worker.status.screen_static": "♻️ 画面に変化はありません",
        "worker.status.screenshot_done": "✅ スクリーンショットの翻訳が完了しました",
        "worker.status.smart_crop": "🧭 スマート切り抜きを解析中...",
        "worker.status.scanning_translating": "🔍 スキャンして翻訳中...",
        "worker.status.recognition_error": "❌ 認識エラー",
        "worker.status.crop_retry_full": "🧭 スマート切り抜きの結果が少ないため、画面全体で再試行します...",
        "worker.status.crop_retry_rotate": "選択範囲に文字が見つかりません。回転して再試行しています...",
        "worker.status.crop_retry_zoom": "選択範囲に文字が見つかりません。範囲を広げるか、角度を変えてください。",
        "worker.status.comic_retry": "📚 漫画ページの分割を再試行中...",
        "worker.status.best_threshold": "✨ 最適なしきい値を選択しました：{threshold}",
        "worker.status.ai_big_translation": "🧠 AI で大きな画像を翻訳中...",
        "worker.status.google_translation": "🌐 Google で翻訳中...",
        "worker.status.batch_translate": "{icon} {prefix} {count} 件をまとめて翻訳中...",
        "worker.status.segment_progress": "{icon} {prefix} {current}/{total}",
        "worker.status.translation_done": "✅ 翻訳が完了しました",
        "worker.status.translation_failed": "翻訳が完了しませんでした。エンジン設定と接続を確認して再試行してください。",
        "worker.status.translation_incomplete": "一部のテキストは原文のままです。翻訳エンジンを確認して再試行してください。",
        "worker.status.translation_rate_limited": "Google 翻訳は現在利用制限中です。時間をおいて再試行するか、別の翻訳エンジンに切り替えてください。",
        "worker.status.no_text": "認識できる文字がありません。鮮明な文字の範囲を選択してください。",
        "controller.hint.region_empty": "読みやすい外国語の文字を囲み、「今すぐ翻訳」を押してください。",
        "controller.engine.google": "Google 翻訳",
        "controller.engine.local_gemma": "ローカル Gemma",
        "controller.engine.online_gemma": "オンライン Gemma",
        "controller.engine.luna": "Luna",
        "controller.engine.summary": "{name} · {state}",
        "controller.engine.state.internet": "ネット接続が必要",
        "controller.engine.state.configured": "キー設定済み・接続未確認",
        "controller.engine.state.setup": "API キーが必要",
        "controller.engine.state.preparing": "モデル準備中",
        "controller.engine.state.ready": "モデル準備完了",
        "controller.engine.state.failed": "モデルの確認が必要",
        "controller.engine.state.unverified": "モデル未準備",
        "controller.engine.pending": "{name} の設定待ち",
        "controller.engine.change": "エンジン変更",
        "controller.engine.settings_description": "翻訳エンジンの設定で必要条件とデータの送信先を確認",
        "controller.engine.data.google": "認識した文字を Google に送信します。クラウド OCR 有効時は画像も送信します。",
        "controller.engine.data.local_gemma": "ローカルモデルで処理します。クラウド OCR、リモート接続、オンラインの代替処理では内容を送信する場合があります。",
        "controller.engine.data.online_gemma": "文字や画像を Google に送信します。他の代替処理はエンジン設定によります。",
        "controller.engine.data.luna": "文字や画像を OpenAI に送信します。他の代替処理はエンジン設定によります。",
    },
}


def normalize_ui_language(language: Any, fallback: str = DEFAULT_UI_LANGUAGE) -> str:
    candidate = str(language or "").strip()
    if not candidate:
        return fallback
    normalized = _LANGUAGE_ALIASES.get(candidate.lower(), candidate)
    if normalized in SUPPORTED_UI_LANGUAGES:
        return normalized
    if normalized.lower().startswith("zh"):
        return "zh-TW"
    if normalized.lower().startswith("en"):
        return "en"
    if normalized.lower().startswith("ja"):
        return "ja"
    return fallback


def get_translation_target_lang(ui_language: Any, fallback: str = DEFAULT_UI_LANGUAGE) -> str:
    normalized = normalize_ui_language(ui_language, fallback=fallback)
    # 如果UI是英文，翻譯目標設為英文
    if normalized == "en":
        return "en"
    if normalized == "ja":
        return "ja"
    # 如果UI是中文，翻譯目標設為繁體中文
    elif normalized == "zh-TW":
        return "zh-TW"
    return "zh-TW"


def fallback_text(value: Any, fallback: Any = "") -> str:
    text = str(value or "").strip()
    if text:
        return text
    return str(fallback or "")


def tr(key: str, language: Any = DEFAULT_UI_LANGUAGE, fallback: str | None = None, **params: Any) -> str:
    normalized = normalize_ui_language(language)
    catalog = _TRANSLATIONS.get(normalized, {})
    default_catalog = _TRANSLATIONS.get(DEFAULT_UI_LANGUAGE, {})
    text = catalog.get(key) or default_catalog.get(key) or fallback or key
    if params:
        try:
            text = text.format(**params)
        except Exception:
            pass
    return text
